'use strict';
const EMT_PRODUCTS=[
  {id:1,name:"Classic Sourdough Loaf",slug:"sourdough",category:"breads",price:65,priceUnit:"per loaf",rating:4.9,reviews:124,available:true,dietary:["vegan","dairy-free"],tags:["fresh","artisan","fermented"],description:"72-hour cold-fermented sourdough, stone-baked to perfection. Deep flavour, open crumb, crackling crust.",shortDescription:"72-hour fermented, stone-baked. Open crumb, crackling crust.",image:"images/sourdough.jpg",imageAlt:"Golden sourdough loaf with deeply scored crust on a wooden board",leadTime:"Same day (order by 08:00)",featured:true},
  {id:2,name:"Ciabatta Loaf",slug:"ciabatta",category:"breads",price:55,priceUnit:"per loaf",rating:4.7,reviews:89,available:true,dietary:["vegan"],tags:["fresh","italian","artisan"],description:"Classic Italian ciabatta with crisp crust and open, chewy crumb.",shortDescription:"Crisp crust, open chewy crumb. Great for sandwiches.",image:"images/ciabatta.jpg",imageAlt:"Ciabatta rolls with crisp exterior and airy crumb",leadTime:"Tue, Thu & Sat",featured:false},
  {id:3,name:"Dark Rye Bread",slug:"dark-rye",category:"breads",price:75,priceUnit:"per loaf",rating:4.8,reviews:67,available:true,dietary:["vegan","high-fibre"],tags:["hearty","rye","healthy"],description:"Dense, richly flavoured dark rye with caraway seeds. High fibre.",shortDescription:"Dense, hearty rye. High fibre. Caraway seeds.",image:"images/rye-bread.jpg",imageAlt:"Dark rye loaf sliced to reveal dense crumb with caraway seeds",leadTime:"Wed & Sat",featured:false},
  {id:4,name:"Butter Croissants (6-pack)",slug:"croissants",category:"pastries",price:135,priceUnit:"per 6-pack",rating:4.9,reviews:201,available:true,dietary:["vegetarian"],tags:["breakfast","french","buttery","flaky"],description:"French-style croissants made with South African grass-fed butter. 72 layers of flaky golden perfection.",shortDescription:"72 flaky layers, grass-fed butter. Four flavours.",image:"images/croissants.jpg",imageAlt:"Golden butter croissants in a basket showing flaky layers",leadTime:"Daily until sold out",featured:true},
  {id:5,name:"Assorted Muffins (6-pack)",slug:"muffins",category:"pastries",price:110,priceUnit:"per 6-pack",rating:4.6,reviews:156,available:true,dietary:["vegetarian","gf-option","vegan-option"],tags:["daily","variety","breakfast"],description:"Rotating seasonal selection: blueberry, double chocolate, bran & raisin, lemon poppy seed.",shortDescription:"Daily rotating flavours. GF & vegan options available.",image:"images/muffins.jpg",imageAlt:"Assorted muffins in a paper-lined tray",leadTime:"Daily",featured:false},
  {id:6,name:"Birthday Celebration Cake",slug:"birthday-cake",category:"cakes",price:450,priceUnit:"from (10 portions)",rating:5.0,reviews:88,available:true,dietary:["gf-option","vegan-option"],tags:["custom","bespoke","birthday"],description:"Fully bespoke birthday cakes in any size, flavour, and design.",shortDescription:"Fully bespoke. Choose size, flavour, and design.",image:"images/birthday-cake.jpg",imageAlt:"Three-tier birthday cake with buttercream rosettes",leadTime:"Min 5 business days",featured:true},
  {id:7,name:"Wedding Cake",slug:"wedding-cake",category:"cakes",price:2500,priceUnit:"from (2-tier, 50 portions)",rating:5.0,reviews:37,available:true,dietary:["custom"],tags:["wedding","luxury","tiered","fondant"],description:"Timeless fondant or textured buttercream tiers. Free consultation and tasting session included.",shortDescription:"Free consultation & tasting. Delivery & setup included.",image:"images/wedding-cake.jpg",imageAlt:"Elegant five-tier white fondant wedding cake with cascading roses",leadTime:"Min 6 weeks notice",featured:true},
  {id:8,name:"Corporate Branded Cake",slug:"corporate-cake",category:"cakes",price:650,priceUnit:"from",rating:4.9,reviews:42,available:true,dietary:["custom"],tags:["corporate","branded","events"],description:"Company colours, logo and messaging. Edible printing and hand-piping available.",shortDescription:"Logo, brand colours, edible print. 20–50+ portions.",image:"images/corporate-cake.jpg",imageAlt:"Sleek corporate cake in company brand colours with edible logo",leadTime:"Min 7 business days",featured:false},
  {id:9,name:"Meeting & Event Platters",slug:"event-platters",category:"corporate",price:85,priceUnit:"per person (min 10)",rating:4.8,reviews:63,available:true,dietary:["custom","halal-option"],tags:["corporate","bulk","meetings","professional"],description:"Professionally arranged platters of artisan breads, pastries, sweet treats and preserves.",shortDescription:"Professional platters. Min 10 persons. Delivered.",image:"images/corporate-catering.jpg",imageAlt:"Large professional platter of assorted pastries and artisan breads",leadTime:"Min 48 hours notice",featured:true},
  {id:10,name:"Branded Gift Boxes",slug:"gift-boxes",category:"corporate",price:180,priceUnit:"per box (min 5)",rating:4.9,reviews:28,available:true,dietary:["custom"],tags:["gifts","branded","corporate","hamper"],description:"Individually boxed selections of our finest baked goods with branded ribbon and tissue paper.",shortDescription:"Branded packaging, ribbon, tissue. Min 5 boxes.",image:"images/corporate-catering.jpg",imageAlt:"Individually boxed gift sets with branded ribbon and tissue paper",leadTime:"Min 5 business days",featured:false}
];
